# Generated by Django 4.2 on 2023-05-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='classbatch',
        ),
        migrations.AddField(
            model_name='learner',
            name='classbatch',
            field=models.ManyToManyField(null=True, to='rosters.classbatch'),
        ),
    ]
