# Generated by Django 4.2 on 2023-05-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_remove_learner_classbatch_learner_classbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='secret_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='classbatch',
            field=models.ManyToManyField(to='rosters.classbatch'),
        ),
    ]
