# Generated by Django 4.2 on 2023-05-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_learner_secret_id_alter_learner_classbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='classbatch',
            field=models.ManyToManyField(related_name='learners', to='rosters.classbatch'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='secret_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
